config/routes.rb
Babytracks::Application.routes.draw do
  devise_for :users

  resources :events
  resources :users
  root :to => "events#index"

end

app/models/event.rb
class Event < ActiveRecord::Base
  validates_presence_of :event_type, :message => "You must select an event to save"
  belongs_to :user
  validates_presence_of :user

  
  scope :by_user, lambda {|user| 
    where("events.user_id = ?", user.id)
  }
  scope :feedings, lambda {
    where("events.event_type = ?", 'feeding')
  }

  scope :diapers, lambda {
    where("events.event_type = ?", 'diaper')
  }

  scope :arranged_by_day, lambda{
    group("DATE(events.created_at)")
  }

  scope :by_date, lambda {|date|
    begin_day = DateTime.parse(date).beginning_of_day
    end_day = DateTime.parse(date).end_of_day

    where("events.created_at >= ? AND events.created_at <= ?", begin_day, end_day)
  }
  scope :by_days_ago, lambda {|num|
    num = num.to_i
    begin_day = DateTime.now.beginning_of_day - num.days
    end_day = DateTime.now.end_of_day - num.days

    where("events.created_at >= ? AND events.created_at <= ?", begin_day, end_day)
  }
  scope :today, lambda {
    begin_today = DateTime.now.beginning_of_day
    end_today = DateTime.now.end_of_day

    where("events.created_at >= ? AND events.created_at <= ?", begin_today, end_today)
  }
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_many :events

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate_user!

  # GET /events
  # GET /events.xml
  def index
    if params[:date]
      @current = DateTime.parse(params[:date])
    else 
      @current = DateTime.now
    end
    @events = Event.by_user(current_user).by_date(@current.to_s).order('created_at DESC')
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @events }
    end
  end

  # GET /events/1
  # GET /events/1.xml
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @event }
    end
  end

  # GET /events/new
  # GET /events/new.xml
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.xml
  def create
    params[:event][:user_id] = current_user.id
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to(events_path(:date => params[:event][:created_at]), :notice => 'Event was successfully created.') }
        format.xml  { render :xml => @event, :status => :created, :location => @event }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.xml
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to(events_path, :notice => 'Event was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.xml
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to(events_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.xml
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def pretty_date(date, options = {})
    unless date.nil?
      if options[:time] == true
        date.strftime("%b %d, %Y %I:%M %p")
      else
        date.strftime("%b %d, %Y")
      end
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def google_api_graph(target_date)
    before_today = (Date.today - Date.parse(target_date.to_s)).to_i

    feedings = Event.by_user(current_user).feedings.arranged_by_day.size
    diapers = Event.by_user(current_user).diapers.arranged_by_day.size 

      max_d = diapers.max[1] rescue 0
      max_f = feedings.max[1] rescue 0

    if max_d > max_f
      max = max_d
    else
      max = max_f
    end

    start_date = Date.today - (6 + before_today).days
    end_date = Date.today + ( -before_today).days
    date_range = (start_date..end_date).to_a

    date_range = date_range.to_a
    if feedings
      feeding_vals = date_range.collect{|d| feedings[d.to_s].to_i}
    else
      feeding_vals = []
    end

    if diapers
      diaper_vals = date_range.collect{|d| diapers[d.to_s].to_i}
    else
      diapers_vals = []
    end

    # from http://imagecharteditor.appspot.com/
    url = %W(http://chart.apis.google.com/chart
       ?chxl=0:#{date_range.inject(""){|res,e| res + "|" + e.strftime('%a %d')}}
       &chs=640x220
       &chxr=1,0,#{max}
       &chxt=x,y
       &chds=0,0,0,#{max},0,0,0,#{max}
       &cht=lxy
       &chg=0,10,0,0
       &chco=3072F3,FF0000
       &chd=t:-1|#{feeding_vals.join(',')}|-1|#{diaper_vals.join(',')}
       &chdl=Feedings|Diapers
       &chdlp=b
       &chls=2|2
       &chma=5,5,5,25).to_s
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <% unless @event.new_record? %>
      <%= f.datetime_select :created_at %><br />
    <% end %>
    <%= f.select :event_type, options_for_select([['Feeding', 'feeding'],['Diaper', 'diaper']], params[:event_type] || @event.event_type) %>
    <br/>
    <%= f.submit :Save %>
  </div>
<% end %>

app/views/events/_inline_form.html.erb
<div class="actions">
  <%= Event.send("#{event_type.pluralize}").by_date(@current.to_s).size %> today

  <%= form_for Event.new,:html => { :id=> "x_#{event_type}_form" } do |f| %>
    <%= f.hidden_field :event_type, :value => event_type %>
    <%= f.hidden_field :created_at, :value => @current.to_s %>
    <%= f.submit event_type.titleize %>
  <% end %>
</div>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<div id="graph_container">
  <img src="<%= google_api_graph(@current) %>" id="x_graph_image"/>
</div>

<div id="record-events" >
  <%= render "inline_form",  {:event_type => "feeding" } %>
  <%= render "inline_form", {:event_type => "diaper" } %>
</div>

<div id="history">
<h2>Baby Events for <%= pretty_date(@current ) %></h2>
  <div class="pagination">
    <%= link_to '&lt;&lt; Previous'.html_safe, :date => @current.yesterday.strftime('%Y-%m-%d') %>
    <%= link_to 'Next &gt;&gt;'.html_safe, :date => @current.tomorrow.strftime('%Y-%m-%d') %>
  </div>
  <dl>
  <% @events.each do |event| %>
  <dt><%= link_to event.event_type.humanize, edit_event_path(event)%></dt>
    <dd><time datetime="<%=event.created_at.to_formatted_s(:db)%>"> <%= event.created_at.to_formatted_s(:long) %></time></dd>
    <dd class="edit-actions"><%=link_to "[x]", event, :confirm => 'Are you sure?', :method => :delete %><br/></dd>
  <% end %>
  </dl>
</div>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Babytracks</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  </head>
<body>
  <ul class="hmenu">
    <%= render 'devise/menu/login_items' %>
  </ul>

  <%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>